/* =====================================================================
   FACE-OFF: A+ CORE 1  —  QUESTION POOL
   Exam: CompTIA A+ 220-1201 (Core 1, V15)
   ---------------------------------------------------------------------
   12 categories x 10 clues = 120 board questions, plus 30 Lightning
   Final questions. Each category's clues run EASIEST first, HARDEST
   last — that ordering becomes the 100 → 500 rows on the board.

     q   = the question students see
     a   = the answer (host screen only)
     alt = other phrasings you'd accept (host hint, optional)
     obj = 220-1201 objective number

   Coverage: every objective from 1.1 through 5.6.
   Domain weights: Mobile 13% · Networking 23% · Hardware 25% ·
                   Virtualization & Cloud 11% · Troubleshooting 28%
   ===================================================================== */

window.FACEOFF_QUESTIONS = {
  categories: [
    { name: "MOBILE DEVICES",
      clues: [
      { q: "This reversible connector is standard on modern Android phones, tablets, and laptops.",
        a: "USB-C",
        obj: "1.1" },
      { q: "This was Apple's proprietary connector before they moved to USB-C.",
        a: "Lightning",
        obj: "1.1" },
      { q: "This short-range wireless technology powers tap-to-pay and works at about 10 centimeters.",
        a: "NFC",
        alt: ["Near Field Communication"],
        obj: "1.1" },
      { q: "This feature lets a phone share its cellular connection with other devices over Wi-Fi.",
        a: "Mobile hotspot",
        alt: ["Tethering"],
        obj: "1.2" },
      { q: "This is the open standard used for wireless charging pads.",
        a: "Qi",
        obj: "1.1" },
      { q: "Name the protocol for OUTGOING mail, and the two common protocols for INCOMING mail.",
        a: "SMTP outgoing; IMAP and POP3 incoming",
        alt: ["SMTP; IMAP/POP3"],
        obj: "1.2" },
      { q: "Give the secure port numbers for IMAP, POP3, and SMTP submission.",
        a: "IMAPS 993, POP3S 995, SMTP submission 587",
        alt: ["993, 995, 587"],
        obj: "1.2" },
      { q: "Explain what MDM software lets an organization do to an enrolled phone.",
        a: "Enforce policy, push and restrict apps, require a passcode or encryption, and remotely lock or wipe the device",
        alt: ["Push policy, remote wipe"],
        obj: "1.2" },
      { q: "Explain the difference between synchronizing to the cloud and synchronizing to the desktop.",
        a: "Cloud sync copies data to a provider's servers and is reachable anywhere; desktop sync copies it to a local computer over cable or local network",
        alt: ["Cloud = provider servers, desktop = local PC"],
        obj: "1.2" },
      { q: "A user enrolls a phone in MDM and corporate email immediately stops working. Name the two most likely causes.",
        a: "The MDM profile pushed new mail settings or a required passcode/encryption policy the user hasn't accepted, or conditional access is blocking the non-compliant device",
        alt: ["Policy not accepted or device non-compliant"],
        obj: "1.2" }
      ] },
    { name: "PORTS & PROTOCOLS",
      clues: [
      { q: "HTTP uses this port.",
        a: "80",
        obj: "2.1" },
      { q: "HTTPS uses this port.",
        a: "443",
        obj: "2.1" },
      { q: "SSH uses this port.",
        a: "22",
        obj: "2.1" },
      { q: "RDP uses this port.",
        a: "3389",
        obj: "2.1" },
      { q: "DNS uses this port.",
        a: "53",
        obj: "2.1" },
      { q: "Name BOTH ports DHCP uses.",
        a: "67 (server) and 68 (client)",
        alt: ["67 and 68"],
        obj: "2.1" },
      { q: "SMB file sharing runs directly on this port.",
        a: "445",
        obj: "2.1" },
      { q: "Name the ports for SNMP polling and SNMP traps.",
        a: "161 for polling, 162 for traps",
        alt: ["161 and 162"],
        obj: "2.1" },
      { q: "Name the plaintext port for FTP control, and the secure alternative that runs over SSH.",
        a: "21 for FTP control; SFTP on 22",
        alt: ["21; SFTP 22"],
        obj: "2.1" },
      { q: "Give one sentence each on how TCP and UDP differ, and one real protocol that uses each.",
        a: "TCP is connection-oriented and acknowledges every segment — HTTPS uses it. UDP is connectionless with no acknowledgement, so it's faster — DHCP or streaming video use it",
        alt: ["TCP reliable/HTTPS, UDP fast/DHCP"],
        obj: "2.1" }
      ] },
    { name: "PORTS & PROTOCOLS II",
      clues: [
      { q: "Telnet uses this port.",
        a: "23",
        alt: ["port 23"],
        obj: "2.1" },
      { q: "SMTP sends mail on this port.",
        a: "25",
        alt: ["port 25"],
        obj: "2.1" },
      { q: "POP3 retrieves mail on this port.",
        a: "110",
        alt: ["port 110"],
        obj: "2.1" },
      { q: "IMAP retrieves mail on this port.",
        a: "143",
        alt: ["port 143"],
        obj: "2.1" },
      { q: "FTP uses port 21 for commands. Name the port it uses for the actual file data.",
        a: "20",
        alt: ["port 20"],
        obj: "2.1" },
      { q: "LDAP uses this port.",
        a: "389",
        alt: ["port 389"],
        obj: "2.1" },
      { q: "LDAPS — the encrypted version — uses this port.",
        a: "636",
        alt: ["port 636"],
        obj: "2.1" },
      { q: "Name BOTH NetBIOS ports and say what each one does.",
        a: "137 name service (UDP) and 139 session service (TCP)",
        alt: ["137 and 139"],
        obj: "2.1" },
      { q: "Explain what a port number actually identifies, and why two services can’t listen on the same one.",
        a: "It identifies the specific service on a host so incoming traffic reaches the right application — and only one listener can bind a given port per protocol on an address",
        alt: ["it identifies the service, and only one program can bind a port"],
        obj: "2.1" },
      { q: "Explain the practical difference between POP3 and IMAP, and give both ports.",
        a: "POP3 (110) downloads mail and usually removes it from the server; IMAP (143) syncs and leaves it there, so several devices stay in step",
        alt: ["POP3 110 downloads, IMAP 143 syncs"],
        obj: "2.1" }
      ] },
    { name: "WIRELESS & INTERNET",
      clues: [
      { q: "Name the three non-overlapping channels in the 2.4 GHz band.",
        a: "1, 6, and 11",
        obj: "2.2" },
      { q: "802.11ac operates in this band only.",
        a: "5 GHz",
        obj: "2.2" },
      { q: "Give the 802.11 designation for Wi-Fi 6.",
        a: "802.11ax",
        obj: "2.2" },
      { q: "Wi-Fi 6E extends Wi-Fi 6 into this additional band.",
        a: "6 GHz",
        obj: "2.2" },
      { q: "This is the strongest current wireless security standard.",
        a: "WPA3",
        obj: "2.2" },
      { q: "Name what LAN, WAN, PAN, and MAN each stand for.",
        a: "Local, Wide, Personal, and Metropolitan Area Network",
        obj: "2.7" },
      { q: "Explain the trade-off between the 2.4 GHz and 5 GHz bands.",
        a: "2.4 GHz travels farther and penetrates walls better but is slower and more congested; 5 GHz is much faster with less interference but shorter range",
        alt: ["2.4 = range, 5 = speed"],
        obj: "2.2" },
      { q: "Name the internet connection type with the highest latency, and explain why.",
        a: "Satellite — the signal has to travel to orbit and back, and weather can disrupt it",
        alt: ["Satellite, distance to orbit"],
        obj: "2.7" },
      { q: "Rank fiber, cable, and DSL by typical speed, and name the medium each uses.",
        a: "Fiber (light through glass) fastest, then cable (coaxial), then DSL (existing phone lines)",
        alt: ["Fiber > cable > DSL"],
        obj: "2.7" },
      { q: "A rural site can't get fiber or cable. Name two viable connection types and the main drawback of each.",
        a: "Satellite (high latency, weather) and cellular/WISP fixed wireless (data caps, line-of-sight or tower distance)",
        alt: ["Satellite and cellular/WISP"],
        obj: "2.7" }
      ] },
    { name: "NETWORK HARDWARE & SOHO",
      clues: [
      { q: "This device connects separate networks and forwards traffic using IP addresses.",
        a: "Router",
        obj: "2.5" },
      { q: "This device forwards frames inside a LAN using MAC addresses.",
        a: "Switch",
        obj: "2.5" },
      { q: "This service automatically hands out IP addresses, masks, gateways, and DNS servers.",
        a: "DHCP",
        obj: "2.3" },
      { q: "This service translates hostnames into IP addresses.",
        a: "DNS",
        obj: "2.3" },
      { q: "Name all three private IPv4 ranges.",
        a: "10.0.0.0/8, 172.16.0.0/12, and 192.168.0.0/16",
        obj: "2.4" },
      { q: "Name the tool that attaches an RJ45 plug, the tool that verifies the wiring, and the tool that finds one cable in a bundle.",
        a: "Crimper, cable tester, and toner probe",
        obj: "2.8" },
      { q: "A device shows an address starting 169.254. Name what that is and what failed.",
        a: "APIPA — the client couldn't reach a DHCP server",
        alt: ["APIPA, DHCP failed"],
        obj: "2.4" },
      { q: "Explain what port forwarding does on a SOHO router and give one example use.",
        a: "It sends traffic arriving on a specific external port to a specific internal host — for example, forwarding 3389 to a PC for Remote Desktop",
        alt: ["Maps external port to internal host"],
        obj: "2.6" },
      { q: "Name which devices should get a static IP on a small network, and why.",
        a: "Servers, printers, and network gear — other devices need to find them at a consistent address",
        alt: ["Servers and printers"],
        obj: "2.6" },
      { q: "Explain the difference between a router's port forwarding and putting a host in the DMZ — and why DMZ is riskier.",
        a: "Port forwarding opens only the ports you specify; a DMZ host is exposed on every port, so a single vulnerable service compromises it",
        alt: ["DMZ exposes everything"],
        obj: "2.6" }
      ] },
    { name: "RAM & STORAGE",
      clues: [
      { q: "This is the smaller RAM form factor used in laptops.",
        a: "SODIMM",
        obj: "3.1" },
      { q: "This RAM type detects and corrects single-bit memory errors and is used in servers.",
        a: "ECC RAM",
        alt: ["Error Correcting Code"],
        obj: "3.1" },
      { q: "Name the two main advantages of an SSD over a traditional hard drive.",
        a: "Much faster access with no moving parts to fail, plus lower power and no noise",
        alt: ["Faster, no moving parts"],
        obj: "3.8" },
      { q: "This M.2 drive interface is far faster than SATA because it talks over PCIe.",
        a: "NVMe",
        obj: "3.8" },
      { q: "Explain why DDR4 and DDR5 modules are not interchangeable.",
        a: "Different pin counts, different notch position, and different voltage — the board physically and electrically only takes one",
        alt: ["Different notch and pins"],
        obj: "3.1" },
      { q: "Explain what dual-channel memory does and what you must do to get it.",
        a: "It doubles the memory bus width for more bandwidth — install matched modules in the correct paired slots",
        alt: ["Doubles bandwidth, matched pairs"],
        obj: "3.1" },
      { q: "Describe RAID 0 and RAID 1, and what each gives you.",
        a: "RAID 0 stripes for speed and capacity with NO redundancy; RAID 1 mirrors for redundancy with no capacity gain",
        alt: ["0 = striping, 1 = mirroring"],
        obj: "3.8" },
      { q: "Give the minimum number of drives for RAID 5 and explain what it can survive.",
        a: "Three drives — striping with distributed parity, surviving one drive failure",
        alt: ["3 drives, one failure"],
        obj: "3.8" },
      { q: "A server must survive TWO simultaneous drive failures. Name two RAID levels that can, and the trade-off.",
        a: "RAID 6 (dual parity) or RAID 10 (mirrored stripes, if the failures are in different mirrors) — both cost more usable capacity",
        alt: ["RAID 6 or RAID 10"],
        obj: "3.8" },
      { q: "Explain what the page file is and the symptom you see when RAM is insufficient.",
        a: "Disk space used as overflow virtual memory — when RAM runs short the system pages constantly to disk and slows to a crawl",
        alt: ["Virtual memory; thrashing/slowdown"],
        obj: "3.1" }
      ] },
    { name: "MOTHERBOARDS, CPUs & POWER",
      clues: [
      { q: "This is the standard full-size desktop motherboard form factor.",
        a: "ATX",
        obj: "3.4" },
      { q: "This connector delivers main power from the PSU to the motherboard.",
        a: "The 24-pin ATX connector",
        alt: ["24-pin"],
        obj: "3.5" },
      { q: "This coin cell keeps the BIOS/UEFI settings and clock alive with the machine unplugged.",
        a: "CMOS battery (CR2032)",
        alt: ["CR2032"],
        obj: "3.4" },
      { q: "A graphics card goes in this slot type.",
        a: "PCIe x16",
        obj: "3.4" },
      { q: "Explain the difference between LGA and PGA CPU sockets.",
        a: "LGA puts the pins in the socket and flat contacts on the CPU; PGA puts the pins on the CPU itself",
        alt: ["LGA pins in socket, PGA pins on chip"],
        obj: "3.4" },
      { q: "Name what must go between a CPU and its heat sink, and what happens without it.",
        a: "Thermal paste — without it heat doesn't transfer and the CPU throttles or shuts down",
        alt: ["Thermal paste"],
        obj: "3.4" },
      { q: "Name the rating that tells you how efficiently a power supply converts AC to DC.",
        a: "80 PLUS certification (Bronze through Titanium)",
        alt: ["80 PLUS"],
        obj: "3.5" },
      { q: "Explain the benefit of a modular power supply.",
        a: "You attach only the cables you need, so there's less clutter and better airflow",
        alt: ["Only use needed cables"],
        obj: "3.5" },
      { q: "Name the dedicated CPU power connector and the newer high-power GPU connector.",
        a: "The EPS 4+4-pin (8-pin) for the CPU; 12VHPWR / 12V-2x6 for modern GPUs",
        alt: ["EPS 8-pin and 12VHPWR"],
        obj: "3.5" },
      { q: "A build draws about 450 W at peak. Explain what wattage PSU you'd choose and why.",
        a: "Roughly 650–750 W — headroom keeps the unit in its efficient range, handles transient spikes, and leaves room to upgrade",
        alt: ["650-750W for headroom"],
        obj: "3.5" }
      ] },
    { name: "CABLES & DISPLAYS",
      clues: [
      { q: "This connector terminates a copper Ethernet cable.",
        a: "RJ45",
        obj: "3.3" },
      { q: "This is the standard digital video and audio connector on TVs and monitors.",
        a: "HDMI",
        obj: "3.3" },
      { q: "This older 15-pin connector carries analog video only.",
        a: "VGA",
        obj: "3.3" },
      { q: "Name the two cables a traditional SATA hard drive needs.",
        a: "A SATA data cable and a SATA power cable",
        obj: "3.3" },
      { q: "Name any two fiber optic connector types.",
        a: "LC, SC, or ST (any two)",
        obj: "3.3" },
      { q: "Explain the main advantage of an IPS panel over a TN panel.",
        a: "Far better color accuracy and viewing angles — TN's advantage is faster response and lower cost",
        alt: ["Better color and viewing angles"],
        obj: "3.2" },
      { q: "Explain what OLED does that an LCD cannot, and its main weakness.",
        a: "Each pixel emits its own light, so blacks are truly black with infinite contrast — but it's prone to burn-in",
        alt: ["Per-pixel light, true black; burn-in"],
        obj: "3.2" },
      { q: "Define refresh rate and resolution, and say which one a gamer cares about for smooth motion.",
        a: "Refresh rate is screen redraws per second (Hz); resolution is pixel count. Motion smoothness comes from refresh rate",
        alt: ["Hz vs pixels; refresh rate"],
        obj: "3.2" },
      { q: "This connector carries video, data, and power on one port and can drive multiple displays.",
        a: "Thunderbolt (over USB-C)",
        alt: ["USB-C / Thunderbolt"],
        obj: "3.3" },
      { q: "A user needs 4K at 120 Hz on one cable. Name the two standards that support it.",
        a: "HDMI 2.1 or DisplayPort 1.4 and later",
        alt: ["HDMI 2.1 / DP 1.4"],
        obj: "3.3" }
      ] },
    { name: "PRINTERS",
      clues: [
      { q: "This printer type uses toner, a drum, and heat to fuse the image to the page.",
        a: "Laser printer",
        obj: "3.6" },
      { q: "This printer type sprays liquid ink through nozzles.",
        a: "Inkjet",
        obj: "3.6" },
      { q: "This printer uses heat on special paper and is common for receipts.",
        a: "Thermal printer",
        obj: "3.6" },
      { q: "This printer strikes a ribbon and is still used for multipart carbon forms.",
        a: "Impact printer",
        alt: ["Dot matrix"],
        obj: "3.6" },
      { q: "This setting prints on both sides of the page automatically.",
        a: "Duplex",
        alt: ["Duplexing"],
        obj: "3.6" },
      { q: "Name the component in a laser printer that bonds toner permanently to the paper with heat and pressure.",
        a: "The fuser",
        alt: ["Fuser assembly"],
        obj: "3.7" },
      { q: "Name three routine maintenance tasks for a laser printer.",
        a: "Replace the toner cartridge, apply the maintenance kit, clean the internals, and calibrate (any three)",
        alt: ["Toner, maintenance kit, clean, calibrate"],
        obj: "3.7" },
      { q: "Name the maintenance an inkjet needs when output has gaps or misaligned colors.",
        a: "Clean the print heads and calibrate/align them",
        alt: ["Head cleaning and alignment"],
        obj: "3.7" },
      { q: "Give the seven steps of the laser imaging process, in order.",
        a: "Processing, charging, exposing, developing, transferring, fusing, cleaning",
        alt: ["Process, charge, expose, develop, transfer, fuse, clean"],
        obj: "3.7" },
      { q: "Explain the difference between sharing a printer from a PC and using a dedicated print server.",
        a: "A shared printer only works while that host PC is on and handles the queue; a print server is always available and manages queues and drivers centrally",
        alt: ["Host PC must stay on vs always available"],
        obj: "3.6" }
      ] },
    { name: "VIRTUALIZATION & CLOUD",
      clues: [
      { q: "This software layer creates and runs virtual machines.",
        a: "A hypervisor",
        obj: "4.1" },
      { q: "Explain the difference between a Type 1 and a Type 2 hypervisor.",
        a: "Type 1 runs directly on the bare metal; Type 2 runs as an application on top of a host OS",
        alt: ["Bare metal vs hosted"],
        obj: "4.1" },
      { q: "In this cloud model you rent virtual machines and manage the OS and applications yourself.",
        a: "IaaS",
        alt: ["Infrastructure as a Service"],
        obj: "4.2" },
      { q: "In this cloud model you just use the finished application in a browser — Microsoft 365 is an example.",
        a: "SaaS",
        alt: ["Software as a Service"],
        obj: "4.2" },
      { q: "Name the cloud deployment model that combines on-premises infrastructure with public cloud.",
        a: "Hybrid cloud",
        obj: "4.2" },
      { q: "Name the cloud characteristic that lets resources scale up and back down automatically with demand.",
        a: "Rapid elasticity",
        alt: ["Elasticity"],
        obj: "4.2" },
      { q: "Name the setup where desktops run in the data center and users connect to them remotely.",
        a: "VDI",
        alt: ["Virtual Desktop Infrastructure"],
        obj: "4.1" },
      { q: "Name two legitimate reasons to run a virtual machine on a technician's workstation.",
        a: "Sandboxing suspicious software, testing a build, running a legacy app, or cross-platform development (any two)",
        alt: ["Sandbox, test, legacy app"],
        obj: "4.1" },
      { q: "Name the BIOS/UEFI setting that must be enabled before a hypervisor will run VMs.",
        a: "CPU virtualization extensions — Intel VT-x or AMD-V",
        alt: ["VT-x / AMD-V"],
        obj: "4.1" },
      { q: "Explain the difference between rapid elasticity and metered utilization in cloud billing.",
        a: "Elasticity is the resources scaling with demand; metered utilization is being charged only for what you actually consumed",
        alt: ["Scaling vs pay-per-use"],
        obj: "4.2" }
      ] },
    { name: "TROUBLESHOOTING: HARDWARE",
      clues: [
      { q: "A PC powers on but there's no image and no POST beeps. Name the first two things to check.",
        a: "That the monitor and its cable are on the right input, and that RAM and the GPU are properly seated",
        alt: ["Monitor/cable, then reseat RAM/GPU"],
        obj: "5.1" },
      { q: "There's a burning smell and the system won't power on at all. Name the most likely failed part.",
        a: "The power supply",
        obj: "5.1" },
      { q: "A drive is making a repeated clicking or grinding noise. Name what's happening.",
        a: "Mechanical failure of a hard drive — back it up immediately and replace",
        alt: ["Failing HDD"],
        obj: "5.2" },
      { q: "This drive self-monitoring system warns of impending failure before the drive dies.",
        a: "S.M.A.R.T.",
        alt: ["SMART"],
        obj: "5.2" },
      { q: "A machine shuts down on its own during heavy load but runs fine when idle. Name two likely causes.",
        a: "Overheating from dust, failed fan, or dried thermal paste — or a power supply that can't sustain peak draw",
        alt: ["Overheating or undersized PSU"],
        obj: "5.1" },
      { q: "You see swollen, leaking cylinders on the motherboard. Name them and the fix.",
        a: "Bulging capacitors — the board must be replaced",
        alt: ["Distended capacitors, replace board"],
        obj: "5.1" },
      { q: "A PC won't POST right after a RAM upgrade. Name the three things to check, in order.",
        a: "Reseat the modules, confirm the correct type and speed for the board, and try one module at a time in the primary slot",
        alt: ["Reseat, verify compatibility, test one stick"],
        obj: "5.1" },
      { q: "A RAID 5 array reports 'degraded'. Explain what happened and what to do.",
        a: "One drive failed — data is still available on parity, but replace the drive and let it rebuild before a second one fails",
        alt: ["One drive failed, replace and rebuild"],
        obj: "5.2" },
      { q: "A system reports 'boot device not found' though the drive spins up. Name three things to check.",
        a: "Boot order in UEFI, the data and power cables, and whether the drive is detected in BIOS or the partition/boot record is damaged",
        alt: ["Boot order, cables, drive detection"],
        obj: "5.2" },
      { q: "A PC randomly reboots with no pattern and no error. Explain the order you'd isolate the cause.",
        a: "Check temperatures and fans, then test or swap the PSU, then test RAM, then check the event log and finally the motherboard",
        alt: ["Heat, PSU, RAM, then board"],
        obj: "5.1" }
      ] },
    { name: "TROUBLESHOOTING: DISPLAY & MOBILE",
      clues: [
      { q: "A laptop screen is very dim but you can just make out the image. Name the likely failed part.",
        a: "The backlight (or its inverter on older panels)",
        alt: ["Backlight"],
        obj: "5.3" },
      { q: "A monitor says 'no signal' though the PC is running. Name the first two checks.",
        a: "The input source selected on the monitor, and the video cable connection at both ends",
        alt: ["Wrong input, loose cable"],
        obj: "5.3" },
      { q: "Name the permanent image retention that affects OLED panels showing static content.",
        a: "Burn-in",
        alt: ["Image burn-in"],
        obj: "5.3" },
      { q: "A projector shuts itself off after running a while. Name the most likely cause.",
        a: "Overheating — clogged filter or failed fan",
        alt: ["Overheating"],
        obj: "5.3" },
      { q: "A phone won't charge. Name the three things to check before declaring the battery dead.",
        a: "Try a known-good cable and charger, clean lint out of the charging port, and check for a damaged port",
        alt: ["Cable, port debris, charger"],
        obj: "5.4" },
      { q: "A phone battery is visibly swollen. Explain exactly what to do and what NOT to do.",
        a: "Stop using and charging it immediately, don't puncture or compress it, and dispose of it through proper e-waste/hazmat recycling",
        alt: ["Stop use, don't puncture, recycle properly"],
        obj: "5.4" },
      { q: "A touchscreen responds erratically in one area only. Name two likely causes.",
        a: "A damaged digitizer or a poorly applied screen protector or debris — a cracked screen can also do it",
        alt: ["Digitizer damage or screen protector"],
        obj: "5.4" },
      { q: "A phone gets hot and drains fast even when idle. Name three things to check.",
        a: "A runaway app in the background, weak signal forcing the radio to full power, a failing battery, or a bad charging accessory (any three)",
        alt: ["Background apps, weak signal, battery"],
        obj: "5.4" },
      { q: "A display flickers at certain resolutions but is stable at others. Name the two most likely causes.",
        a: "A refresh rate the panel can't sustain at that resolution, or a cable that lacks the bandwidth for that mode",
        alt: ["Refresh rate or inadequate cable"],
        obj: "5.3" },
      { q: "A laptop shows an image on an external monitor but nothing on its own screen. Explain the diagnosis.",
        a: "The GPU works, so the fault is downstream — check the display toggle/function key first, then the panel, backlight, or the video ribbon cable",
        alt: ["GPU fine; display toggle, then panel/cable"],
        obj: "5.3" }
      ] },
    { name: "TROUBLESHOOTING: NET & PRINT",
      clues: [
      { q: "A PC has no network connectivity at all. Name the very first thing to check.",
        a: "The physical connection — cable seated, link lights on the NIC and switch",
        alt: ["Cable and link lights"],
        obj: "5.5" },
      { q: "A workstation has a 169.254 address. Name the cause.",
        a: "It couldn't reach a DHCP server (APIPA)",
        alt: ["DHCP failure"],
        obj: "5.5" },
      { q: "Printouts come out as pages of random characters. Name the most likely cause.",
        a: "The wrong or corrupted print driver",
        alt: ["Wrong driver"],
        obj: "5.6" },
      { q: "A laser printer's output is faded across the whole page. Name the two most likely causes.",
        a: "Low toner, or the density/economy setting is turned down",
        alt: ["Low toner"],
        obj: "5.6" },
      { q: "Users can reach servers by IP address but not by name. Name the failing service.",
        a: "DNS",
        obj: "5.5" },
      { q: "A laser printer leaves the same vertical line down every page. Name the likely part.",
        a: "A scratched or damaged imaging drum (or debris on it)",
        alt: ["Drum"],
        obj: "5.6" },
      { q: "A faint duplicate of the previous image appears further down each page. Name the fault.",
        a: "Ghost images — a failing drum or fuser that isn't fully cleaning or fusing",
        alt: ["Ghosting; drum or fuser"],
        obj: "5.6" },
      { q: "One workstation gets very slow throughput though the link is up. Name the classic cause and the two error counters that confirm it.",
        a: "A duplex mismatch — late collisions on one side and CRC/FCS errors on the other",
        alt: ["Duplex mismatch"],
        obj: "5.5" },
      { q: "A printer keeps jamming in the same place. Name three things to check.",
        a: "Worn pickup/separation rollers, wrong or damp paper stock, overfilled tray, or debris in the path (any three)",
        alt: ["Rollers, paper type, tray, debris"],
        obj: "5.6" },
      { q: "Wireless drops only in one corner of the building, every afternoon. Explain how you'd diagnose it.",
        a: "Check signal strength and channel usage in that area for interference or co-channel contention, look at what changes in the afternoon (client load, machinery, microwaves), then adjust AP placement, channel, or power",
        alt: ["Survey for interference and load, adjust AP/channel"],
        obj: "5.5" }
      ] }
  ],
  lightning: [
      { q: "Which RAID level has no redundancy at all?",
        a: "RAID 0 (striping)",
        alt: ["RAID 0","0"],
        obj: "3.3" },
      { q: "DHCP failed — what address range does the client give itself?",
        a: "169.254.x.x (APIPA)",
        alt: ["169.254","APIPA"],
        obj: "2.5" },
      { q: "What RAM form factor do laptops use?",
        a: "SODIMM",
        obj: "3.1" },
      { q: "Which RAID level mirrors drives?",
        a: "RAID 1",
        obj: "3.8" },
      { q: "Minimum drives for RAID 5?",
        a: "Three",
        obj: "3.8" },
      { q: "What connector is on a copper Ethernet cable?",
        a: "RJ45",
        obj: "3.3" },
      { q: "Which three 2.4 GHz channels don't overlap?",
        a: "1, 6, and 11",
        obj: "2.2" },
      { q: "What's the 802.11 name for Wi-Fi 6?",
        a: "802.11ax",
        obj: "2.2" },
      { q: "What band does 802.11ac use?",
        a: "5 GHz",
        obj: "2.2" },
      { q: "What battery keeps BIOS settings alive?",
        a: "The CMOS battery (CR2032)",
        alt: ["CR2032"],
        obj: "3.4" },
      { q: "How many pins on the main ATX power connector?",
        a: "24",
        obj: "3.5" },
      { q: "What slot does a graphics card use?",
        a: "PCIe x16",
        obj: "3.4" },
      { q: "What does an address starting 169.254 mean?",
        a: "DHCP failed — APIPA",
        alt: ["APIPA"],
        obj: "2.4" },
      { q: "What goes between a CPU and its heat sink?",
        a: "Thermal paste",
        obj: "3.4" },
      { q: "Type 1 or Type 2 — which hypervisor is bare metal?",
        a: "Type 1",
        obj: "4.1" },
      { q: "Microsoft 365 is which cloud model?",
        a: "SaaS",
        obj: "4.2" },
      { q: "What laser printer part fuses toner to paper?",
        a: "The fuser",
        obj: "3.7" },
      { q: "Which printer type uses a ribbon for carbon forms?",
        a: "Impact / dot matrix",
        obj: "3.6" },
      { q: "What does NFC stand for?",
        a: "Near Field Communication",
        obj: "1.1" },
      { q: "What's the wireless charging standard called?",
        a: "Qi",
        obj: "1.1" },
      { q: "Which protocol sends outgoing mail?",
        a: "SMTP",
        obj: "1.2" },
      { q: "What does SSD stand for?",
        a: "Solid State Drive",
        obj: "3.8" },
      { q: "Which M.2 interface is faster, SATA or NVMe?",
        a: "NVMe",
        obj: "3.8" },
      { q: "What drive system warns of impending failure?",
        a: "S.M.A.R.T.",
        obj: "5.2" },
      { q: "Garbled printer output usually means what?",
        a: "The wrong print driver",
        obj: "5.6" },
      { q: "Which display technology needs a backlight — LCD or OLED?",
        a: "LCD",
        alt: ["LCD needs one, OLED does not"],
        obj: "3.5" },
      { q: "What does VDI stand for?",
        a: "Virtual Desktop Infrastructure",
        obj: "4.1" },
      { q: "Which connection type has the highest latency?",
        a: "Satellite",
        obj: "2.7" },
      { q: "What's the strongest Wi-Fi security standard?",
        a: "WPA3",
        obj: "2.2" },
      { q: "Dim laptop screen with a faint image — what failed?",
        a: "The backlight",
        obj: "5.3" }
  ]
};
